[workspace]
resolver = "2"
members = [
    "crates/ciphera-core",
    "crates/ciphera-cli"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"

# Config for 'dist'
[workspace.metadata.dist]
